### ISSUE TITLE
执行消失的动画时，偶然会崩溃

### ISSUE THREAD

**Issue by sucwaker** [goweii/AnyLayer#19]
java.lang.IllegalStateException: Cannot start this animator on a detached view!
	at android.view.RenderNode.addAnimator(RenderNode.java:799)
	at android.view.RenderNodeAnimator.setTarget(RenderNodeAnimator.java:299)
	at android.view.RenderNodeAnimator.setTarget(RenderNodeAnimator.java:281)
	at android.animation.RevealAnimator.<init>(RevealAnimator.java:37)
	at android.view.ViewAnimationUtils.createCircularReveal(ViewAnimationUtils.java:71)
	at per.goweii.anylayer.AnimatorHelper.createCircularRevealOutAnim(AnimatorHelper.java:339)

**Comment by goweii** [comment]
已修复，更新看下是否仍能复现。
