### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by KelvinQQ** [goweii/AnyLayer#54]
`
2021-12-17 21:49:53.872 14319-14319/com.iflytek.mobile.reader E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.iflytek.mobile.reader, PID: 14319
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.View.findFocus()' on a null object reference
        at per.goweii.anylayer.ViewManager$1.run(ViewManager.java:153)
        at per.goweii.anylayer.utils.Utils$2.onGlobalLayout(Utils.java:202)
        at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:1056)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2663)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1756)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7705)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1029)
        at android.view.Choreographer.doCallbacks(Choreographer.java:852)
        at android.view.Choreographer.doFrame(Choreographer.java:787)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1014)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7510)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
`

**Comment by KelvinQQ** [comment]
调用方式比较正常，但是是在压力点击弹框的外部区域

**Comment by goweii** [comment]
更新4.1.6
